### PR TITLE
Move ActorRef<Actor> -> ActorRef<Message>

### PR DESCRIPTION
**Pull request by slawlor**
This is an RFC PR, because it's a relatively major breaking change on the API, however prevents leaking a lot of other types where only the message type is necessary.

CC: @jsgf

### CODE REVIEW

**Comment by slawlor** [comment]
Note: This is a rather significant breaking change to the API and therefore requires a larger than normal version bump. Should we decide to move forward with this, I'll push a version bump to a 0.8.0 release along with release notes denoting the break

**Comment by slawlor** [comment]
Also one thing to keep note of, this requires the `Message` trait to now require `Sync` not just `Send`.

**Comment by jsgf** [comment]
Is the plan to release this as 0.8? Is this a hard cut-over or would it be possible to make a new 0.7 release which is an API shim over 0.8?

**Comment by slawlor** [comment]
> Is the plan to release this as 0.8? Is this a hard cut-over or would it be possible to make a new 0.7 release which is an API shim over 0.8?

I was planning a hard cut. But I wonder if I could build an actor ref of Self map to an underlying Self:Msg and be a wrapper..

Let me see if I can think of something, but either way I'm not sure I can wrap spawn to return the right type, since that's a static method we control. We'd need two methods to return either the new base type or shim

**Comment by slawlor** [comment]
Ah due to overlapping implementations potentially possible (i.e. a struct that's both `Message` and `Actor`) it appears that the compiler is preventing me from building an alternate implementation for `TActor: Actor` vs `TMessage: Message`. 

@jsgf For a shim layer, do you have any suggests for what might be a helpful pattern? I have a new type idea which is something like

```rust

/// Shim wrapper for ractor <= 0.7.X pattern where the actor ref was a TActor instead of TMessage
#[derive(Clone)]
pub struct OldActorRef<TActor> where TActor: Actor {
    inner: ActorRef<TActor::Msg>,
}

impl<TActor> std::ops::Deref for OldActorRef<TActor>
where
    TActor: Actor,
{
    type Target = ActorRef<TActor::Msg>;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl<TActor> From<ActorCell> for OldActorRef<TActor>
where
    TActor: Actor,
{
    fn from(value: ActorCell) -> Self {
        Self {
            inner: value.into(),
        }
    }
}

impl<TActor> From<ActorRef<TActor::Msg>> for OldActorRef<TActor>
where
    TActor: Actor,
{
    fn from(value: ActorRef<TActor::Msg>) -> Self {
        Self {
            inner: value,
        }
    }
}

impl<TActor> From<OldActorRef<TActor>> for ActorCell
where
    TActor: Actor,
{
    fn from(value: OldActorRef<TActor>) -> Self {
        value.inner.into()
    }
}

impl<TActor> std::fmt::Debug for OldActorRef<TActor>
where
    TActor: Actor,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self.inner)
    }
}

#[cfg(test)]
mod tests {
    use crate::ActorProcessingErr;

    use super::*;

    struct TestActor;

    #[async_trait::async_trait]
    impl Actor for TestActor {
        type Msg = ();
        type State = ();
        type Arguments = ();
        async fn pre_start(&self, _: ActorRef<Self::Msg>, _: ()) -> Result<(), ActorProcessingErr> {
            Ok(())
        }
    }

    #[crate::concurrency::test]
    async fn test_shim_layer() {
        // setup
        let (actor, handle) = Actor::spawn(None, TestActor, ()).await.expect("Failed to spawn actor");

        let old_ref: OldActorRef<TestActor> = actor.into();
        old_ref.send_message(()).expect("Failed to send message");

        // cleanup
        old_ref.stop(None);
        handle.await.unwrap();
    }
}
```

but the actor's internal processing handlers all are expecting `ActorRef<Self::Msg>` not `OldActorRef<Self>`.

**Comment by jsgf** [comment]
As far as review goes, it's a huge diff but fundamentally it looks pretty straightforward. I think the direction is good, and it seems like one of those "it's fine if it compiles" deals. Are there any areas where it didn't seem like a good fit?

For back compat, it would be nice if you could have 0.7 import 0.8 and have something like:

```
impl<T> Actor08 for T where T: Actor07 {
    type Message = <T as Actor07>::Message;
//...
```
but it certainly feels like one of those things where the orphan rule is going to bite you. And while it might be possible to make work in a limited sense, would it actually let you freely intermix 0.7 and 0.8 ractor code, or would it be too limited?  And how much effort is it to do the transform? If it's just a matter of propagating a new type in ActorRef, it seems like it would be a bit fiddly/tedious but basically compiler-error driven, no?

**Comment by slawlor** [comment]
> Are there any areas where it didn't seem like a good fit?

I think overall, this is the best path forward since really holders of an `ActorRef<_>` can only really do 1 thing, send messages to actors. There's no access to state, the actor's properties, the startup arguments, etc. Therefore only leaking 1 type in the ActorRef, for the message type, makes the most sense (to me). It's also more traditional with the Erlang patterns, since you don't know the listening actor just the message you want to send, so in spirit I think it's the right move.

> would it actually let you freely intermix 0.7 and 0.8 ractor code, or would it be too limited 

In theory this should be possible, since all the primatives are Tokio based, but to have it all in one crate means

1. Saving all existing linked code such that the existing types don't change, but we come up with some new trait names for actor's using `ActorRef<Message>`, but that will get very messy I think to keep everything in-sync. `ActorCell` is the same, but the `ActorRef` is high visibility. 
2. Forcing the old code to a new type (like `Actor07`, `ActorRef07`, `ActorRuntime07`) and making people import the type and alias it to not have breaking code
```rust
use ractor::Actor07 as Actor;
```
etc.

Beyond a *lot* of duplicated code, there's not really any risk here and should intermix fine. It's just a lot of code that should be covered by it's own test suites and needs to now be kept in sync going forward. 

**On the other hand** Doing a hard break between 0.7 -> 0.8 really is just a regex change across a codebase which does `ActorRef<SomeActor>` to `ActorRef<SomeActor::Msg>`. The types are already public, and if you were using 0.7.x you would have dealt with all the actor referencing and public trait types etc already. Personally I'm leaning this way I think which is what this change is proposing. Release notes will also state as such

**Pull request merged**
