### PR TITLE
fix(lint): don't use deny(warnings) in library, rather use it in ci.

### PR DESCRIPTION
**Pull request by simonsan**
It is already being set in CI, so otherwise no changes needed.

https://www.reddit.com/r/rust/comments/f5xpib/psa_denywarnings_is_actively_harmful/

https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html

### CODE REVIEW

**Comment by slawlor** [comment]
I'm fine with this if you also add the rustc flags to the CI

```yaml
runs-on: ubuntu-latest
env:
      RUSTFLAGS: -D warnings
```

**Review by slawlor — CHANGES_REQUESTED** [review]
Please add CI flags

**Comment by simonsan** [comment]
> Please add CI flags

https://github.com/slawlor/ractor/blob/main/.github/workflows/ci.yaml#L67

The appropriate flags are already added, It seems.

**Comment by slawlor** [comment]
Ah I was looking at the flags on build but yes clippy will gate the ci well enough. Approving

**Review by slawlor — APPROVED** [review]
Lgtm

**Pull request merged**
